import type { Metadata } from "next";
import "../../globals.css";
import QueryProvider from "@/components/providers/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/app/context/UserContext";

export const metadata: Metadata = {
  title: "Idea Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <QueryProvider>{children}</QueryProvider>
        </UserProvider>
        <Toaster />
      </body>
    </html>
  );
}
